---

- name: Add host to hostgroup
  command: raidcom add hba_wwn -port {{ item.port }} -hba_wwn {{ item.wwn }} -I{{item.inst}}
  with_items:
      - { port: cl2-c-1, wwn: 100042d70ac00040, inst: 300}
      - { port: cl1-d-1, wwn: 100042d70ac00042, inst: 300}
      - { port: cl2-c-3, wwn: 100042d70ac00040, inst: 301}
      - { port: cl1-d-3, wwn: 100042d70ac00042, inst: 301}

- name: Change nickname to host
  command: raidcom set hba_wwn -port {{ item.port }} -hba_wwn {{ item.wwn }} -wwn_nickname {{ item.nickname }} -I{{item.inst}}
  with_items:
      - { port: cl2-c-1, wwn: 100042d70ac00040, nickname: LOGGSCH05BL07_Port01, inst: 300}
      - { port: cl1-d-1, wwn: 100042d70ac00042, nickname: LOGGSCH05BL07_Port02, inst: 300}
      - { port: cl2-c-3, wwn: 100042d70ac00040, nickname: LOGGSCH05BL07_Port01, inst: 301}
      - { port: cl1-d-3, wwn: 100042d70ac00042, nickname: LOGGSCH05BL07_Port02, inst: 301}
  tags: nickname

#raidcom set hba_wwn -port cl4-l-10 -hba_wwn 50060b0000c2720a -wwn_nickname LOGIXCH01BL03_Port02 -I11

#raidcom add hba_wwn -port cl4-l-10 -hba_wwn 50060b0000c2720a -I11
