---
# tasks file for VSP_Gx00

- include: 00-lockresource.yml
  tags: lock

- include: 01-add_host_to_hostgroup.yml
  when:
    - add_host | default(false)
  tags: add_host

- include: 02-delete_host_from_hostgroup.yml
  when:
    - delete_host | default(false)
  tags: delete_host

- include: 03-delete_lun_path.yml
  when:
    - delete_lun_path | default(false)
  tags: delete_lun_path

- include: 04-delete_ldev.yml
  when:
    - delete_ldev | default(false)
  tags: delete_ldev

- include: 99-unlockresource.yml
  tags: unlock

